### ISSUE TITLE
Backend crashing when adding not included dependenices 

### ISSUE THREAD

**Issue by Luchanso** [Luchanso/dependencies-heatmap#113]

**Comment by Luchanso** [comment]
And dependencies not exist in package.json
```
"errors": [
    {
      "message": "Cannot convert undefined or null to object",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "getDependenciesMapFromGit"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot convert undefined or null to object",
            "    at Function.entries (<anonymous>)",
            "    at GitApi.<anonymous> (/Users/luchanso/dev/github/dependencies-heatmap/packages/backend/src/datasources/git.ts:54:19)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/Users/luchanso/dev/github/dependencies-heatmap/packages/backend/src/datasources/git.ts:5:58)",
            "    at <anonymous>"
          ]
        }
      }
    }
  ],
```

**Comment by Luchanso** [comment]
Fixed in https://github.com/Luchanso/dependencies-heatmap/commit/a39193e6169ced11cd152b260abf23833937b377
